apiVersion: v1
kind: Service
metadata:
  name: locust-master-service
spec:
  type: NodePort
  selector:
    app: locust-master
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8089
      nodePort: 30000
    - name: report
      protocol: TCP
      port: 5557
