apiVersion: 1

datasources:
  - name: InfluxDB_v1
    type: influxdb
    access: server
    database: locust
    # user: grafana
    # password: grafana
    url: http://localhost:8086
    jsonData:
      httpMode: GET