apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master-deployment
  labels:
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust-master 
        image: majikjohnson/tn-locust:testing
        imagePullPolicy: Always
        args: ["-f", "/opt/locust/locustfiles/reporting.py"]
        ports:
        - containerPort: 8089
        - containerPort: 5557
