apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker-deployment
  labels:
    app: locust-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      volumes:
      - name: nfs-pv-locustfiles
        persistentVolumeClaim:
          claimName: nfs-pv-claim
      containers:
      - name: locust-worker 
        image: majikjohnson/tn-locust:testing
        imagePullPolicy: Always
        args: ["-f", "/mnt/locust/locustfiles/reporting.py", "--worker", "--master-host", "locust-master-service"]
        volumeMounts:
        - mountPath: "/mnt/"
          name: nfs-pv-locustfiles
