apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master-deployment
  labels:
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      volumes:
      - name: nfs-pv-locustfiles
        persistentVolumeClaim:
          claimName: nfs-pv-claim
      containers:
      - name: locust-master 
        image: majikjohnson/tn-locust:testing
        imagePullPolicy: Always
        args: ["-f", "/mnt/locust/locustfiles/reporting.py"]
        ports:
        - containerPort: 8089
        - containerPort: 5557
        volumeMounts:
        - mountPath: "/mnt/locust/"
          name: nfs-pv-locustfiles
